# Generated by Django 4.1.7 on 2023-02-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'verbose_name': 'Poll'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name': 'Url'},
        ),
        migrations.AlterField(
            model_name='polls',
            name='question',
            field=models.CharField(max_length=256, verbose_name='Question'),
        ),
    ]
