# Generated by Django 4.1.7 on 2023-02-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_parser', '0002_alter_polls_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='question',
            field=models.TextField(blank=True, max_length=256, verbose_name='Question'),
        ),
    ]
